/*
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import racketEjemplo.ui.internal.RacketEjemploActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyRacketExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RacketEjemploActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RacketEjemploActivator activator = RacketEjemploActivator.getInstance();
		return activator != null ? activator.getInjector(RacketEjemploActivator.EDU_UPB_LP_ISC_MYRACKET) : null;
	}

}
