/*
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyRacketScopeProvider extends DelegatingScopeProvider {
}
