/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.elErrorCosmicoDePaserj;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ElErrorCosmicoDePaserjFactory
 * @model kind="package"
 * @generated
 */
public interface ElErrorCosmicoDePaserjPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "elErrorCosmicoDePaserj";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.edu/lp/isc/ElErrorCosmicoDePaserj";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "elErrorCosmicoDePaserj";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ElErrorCosmicoDePaserjPackage eINSTANCE = edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.MyRacketProgramImpl <em>My Racket Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.MyRacketProgramImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getMyRacketProgram()
   * @generated
   */
  int MY_RACKET_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Defines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_RACKET_PROGRAM__DEFINES = 0;

  /**
   * The feature id for the '<em><b>Executions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_RACKET_PROGRAM__EXECUTIONS = 1;

  /**
   * The number of structural features of the '<em>My Racket Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_RACKET_PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.DefineImpl <em>Define</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.DefineImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getDefine()
   * @generated
   */
  int DEFINE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__BODY = 2;

  /**
   * The number of structural features of the '<em>Define</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 2;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.SimpleExpressionImpl <em>Simple Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.SimpleExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getSimpleExpression()
   * @generated
   */
  int SIMPLE_EXPRESSION = 3;

  /**
   * The number of structural features of the '<em>Simple Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.IntExpressionImpl <em>Int Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.IntExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getIntExpression()
   * @generated
   */
  int INT_EXPRESSION = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION__VALUE = SIMPLE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION_FEATURE_COUNT = SIMPLE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ArithExpressionImpl <em>Arith Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ArithExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getArithExpression()
   * @generated
   */
  int ARITH_EXPRESSION = 5;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__OP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__ARGS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Arith Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.IfExpressionImpl <em>If Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.IfExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getIfExpression()
   * @generated
   */
  int IF_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__COND = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__THEN = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sino</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__SINO = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.FunctionCallExpressionImpl <em>Function Call Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.FunctionCallExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getFunctionCallExpression()
   * @generated
   */
  int FUNCTION_CALL_EXPRESSION = 7;

  /**
   * The feature id for the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_EXPRESSION__FUNCTION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_EXPRESSION__ARGS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Function Call Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.StringExpressionImpl <em>String Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.StringExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getStringExpression()
   * @generated
   */
  int STRING_EXPRESSION = 8;

  /**
   * The feature id for the '<em><b>St</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_EXPRESSION__ST = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ParamsExpressionImpl <em>Params Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ParamsExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getParamsExpression()
   * @generated
   */
  int PARAMS_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS_EXPRESSION__NAME = 0;

  /**
   * The number of structural features of the '<em>Params Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ParamsCallExpressionImpl <em>Params Call Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ParamsCallExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getParamsCallExpression()
   * @generated
   */
  int PARAMS_CALL_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS_CALL_EXPRESSION__FUNCTION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Params Call Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS_CALL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanExpressionImpl <em>Boolean Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getBooleanExpression()
   * @generated
   */
  int BOOLEAN_EXPRESSION = 11;

  /**
   * The number of structural features of the '<em>Boolean Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanConstantImpl <em>Boolean Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanConstantImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getBooleanConstant()
   * @generated
   */
  int BOOLEAN_CONSTANT = 12;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_CONSTANT__BOOL = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_CONSTANT_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanOpExpressionImpl <em>Boolean Op Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanOpExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getBooleanOpExpression()
   * @generated
   */
  int BOOLEAN_OP_EXPRESSION = 13;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_OP_EXPRESSION__OP = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_OP_EXPRESSION__ARGS = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Boolean Op Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_OP_EXPRESSION_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ComparisonExpressionImpl <em>Comparison Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ComparisonExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getComparisonExpression()
   * @generated
   */
  int COMPARISON_EXPRESSION = 14;

  /**
   * The feature id for the '<em><b>Evaluator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXPRESSION__EVALUATOR = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXPRESSION__ARGS = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Comparison Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXPRESSION_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.StringEqualsExpressionImpl <em>String Equals Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.StringEqualsExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getStringEqualsExpression()
   * @generated
   */
  int STRING_EQUALS_EXPRESSION = 15;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_EQUALS_EXPRESSION__OP = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_EQUALS_EXPRESSION__ARGS = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>String Equals Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_EQUALS_EXPRESSION_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListIsEmptyExpressionImpl <em>List Is Empty Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListIsEmptyExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListIsEmptyExpression()
   * @generated
   */
  int LIST_IS_EMPTY_EXPRESSION = 16;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_IS_EMPTY_EXPRESSION__LIST = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List Is Empty Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_IS_EMPTY_EXPRESSION_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListExpressionImpl <em>List Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListExpression()
   * @generated
   */
  int LIST_EXPRESSION = 17;

  /**
   * The feature id for the '<em><b>Simple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_EXPRESSION__SIMPLE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.SimpleListImpl <em>Simple List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.SimpleListImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getSimpleList()
   * @generated
   */
  int SIMPLE_LIST = 18;

  /**
   * The feature id for the '<em><b>Linked</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_LIST__LINKED = 0;

  /**
   * The number of structural features of the '<em>Simple List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.LinkedListImpl <em>Linked List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.LinkedListImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getLinkedList()
   * @generated
   */
  int LINKED_LIST = 19;

  /**
   * The feature id for the '<em><b>Head</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINKED_LIST__HEAD = 0;

  /**
   * The feature id for the '<em><b>Tail</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINKED_LIST__TAIL = 1;

  /**
   * The number of structural features of the '<em>Linked List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINKED_LIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListOperationExpressionImpl <em>List Operation Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListOperationExpressionImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListOperationExpression()
   * @generated
   */
  int LIST_OPERATION_EXPRESSION = 20;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPERATION_EXPRESSION__LIST = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List Operation Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPERATION_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListHeadOpImpl <em>List Head Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListHeadOpImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListHeadOp()
   * @generated
   */
  int LIST_HEAD_OP = 21;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_HEAD_OP__LIST = LIST_OPERATION_EXPRESSION__LIST;

  /**
   * The number of structural features of the '<em>List Head Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_HEAD_OP_FEATURE_COUNT = LIST_OPERATION_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListTailOpImpl <em>List Tail Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListTailOpImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListTailOp()
   * @generated
   */
  int LIST_TAIL_OP = 22;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_TAIL_OP__LIST = LIST_OPERATION_EXPRESSION__LIST;

  /**
   * The number of structural features of the '<em>List Tail Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_TAIL_OP_FEATURE_COUNT = LIST_OPERATION_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListConsOpImpl <em>List Cons Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListConsOpImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListConsOp()
   * @generated
   */
  int LIST_CONS_OP = 23;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_CONS_OP__LIST = LIST_OPERATION_EXPRESSION__LIST;

  /**
   * The feature id for the '<em><b>Elem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_CONS_OP__ELEM = LIST_OPERATION_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List Cons Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_CONS_OP_FEATURE_COUNT = LIST_OPERATION_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListLengthOpImpl <em>List Length Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListLengthOpImpl
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListLengthOp()
   * @generated
   */
  int LIST_LENGTH_OP = 24;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_LENGTH_OP__LIST = LIST_OPERATION_EXPRESSION__LIST;

  /**
   * The number of structural features of the '<em>List Length Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_LENGTH_OP_FEATURE_COUNT = LIST_OPERATION_EXPRESSION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.MyRacketProgram <em>My Racket Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>My Racket Program</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.MyRacketProgram
   * @generated
   */
  EClass getMyRacketProgram();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.MyRacketProgram#getDefines <em>Defines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Defines</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.MyRacketProgram#getDefines()
   * @see #getMyRacketProgram()
   * @generated
   */
  EReference getMyRacketProgram_Defines();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.MyRacketProgram#getExecutions <em>Executions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Executions</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.MyRacketProgram#getExecutions()
   * @see #getMyRacketProgram()
   * @generated
   */
  EReference getMyRacketProgram_Executions();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.Define <em>Define</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Define</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.Define
   * @generated
   */
  EClass getDefine();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.Define#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.Define#getName()
   * @see #getDefine()
   * @generated
   */
  EAttribute getDefine_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.Define#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.Define#getParams()
   * @see #getDefine()
   * @generated
   */
  EReference getDefine_Params();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.Define#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.Define#getBody()
   * @see #getDefine()
   * @generated
   */
  EReference getDefine_Body();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.SimpleExpression <em>Simple Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.SimpleExpression
   * @generated
   */
  EClass getSimpleExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.IntExpression
   * @generated
   */
  EClass getIntExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.IntExpression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.IntExpression#getValue()
   * @see #getIntExpression()
   * @generated
   */
  EAttribute getIntExpression_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ArithExpression <em>Arith Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ArithExpression
   * @generated
   */
  EClass getArithExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ArithExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ArithExpression#getOp()
   * @see #getArithExpression()
   * @generated
   */
  EAttribute getArithExpression_Op();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ArithExpression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ArithExpression#getArgs()
   * @see #getArithExpression()
   * @generated
   */
  EReference getArithExpression_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.IfExpression <em>If Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.IfExpression
   * @generated
   */
  EClass getIfExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.IfExpression#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.IfExpression#getCond()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Cond();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.IfExpression#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.IfExpression#getThen()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Then();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.IfExpression#getSino <em>Sino</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sino</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.IfExpression#getSino()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Sino();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.FunctionCallExpression <em>Function Call Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.FunctionCallExpression
   * @generated
   */
  EClass getFunctionCallExpression();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.FunctionCallExpression#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.FunctionCallExpression#getFunction()
   * @see #getFunctionCallExpression()
   * @generated
   */
  EReference getFunctionCallExpression_Function();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.FunctionCallExpression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.FunctionCallExpression#getArgs()
   * @see #getFunctionCallExpression()
   * @generated
   */
  EReference getFunctionCallExpression_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.StringExpression <em>String Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.StringExpression
   * @generated
   */
  EClass getStringExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.StringExpression#getSt <em>St</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>St</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.StringExpression#getSt()
   * @see #getStringExpression()
   * @generated
   */
  EAttribute getStringExpression_St();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ParamsExpression <em>Params Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Params Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ParamsExpression
   * @generated
   */
  EClass getParamsExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ParamsExpression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ParamsExpression#getName()
   * @see #getParamsExpression()
   * @generated
   */
  EAttribute getParamsExpression_Name();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ParamsCallExpression <em>Params Call Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Params Call Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ParamsCallExpression
   * @generated
   */
  EClass getParamsCallExpression();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ParamsCallExpression#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ParamsCallExpression#getFunction()
   * @see #getParamsCallExpression()
   * @generated
   */
  EReference getParamsCallExpression_Function();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanExpression <em>Boolean Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanExpression
   * @generated
   */
  EClass getBooleanExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanConstant <em>Boolean Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Constant</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanConstant
   * @generated
   */
  EClass getBooleanConstant();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanConstant#isBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanConstant#isBool()
   * @see #getBooleanConstant()
   * @generated
   */
  EAttribute getBooleanConstant_Bool();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanOpExpression <em>Boolean Op Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Op Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanOpExpression
   * @generated
   */
  EClass getBooleanOpExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanOpExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanOpExpression#getOp()
   * @see #getBooleanOpExpression()
   * @generated
   */
  EAttribute getBooleanOpExpression_Op();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanOpExpression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.BooleanOpExpression#getArgs()
   * @see #getBooleanOpExpression()
   * @generated
   */
  EReference getBooleanOpExpression_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ComparisonExpression <em>Comparison Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ComparisonExpression
   * @generated
   */
  EClass getComparisonExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ComparisonExpression#getEvaluator <em>Evaluator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Evaluator</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ComparisonExpression#getEvaluator()
   * @see #getComparisonExpression()
   * @generated
   */
  EAttribute getComparisonExpression_Evaluator();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ComparisonExpression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ComparisonExpression#getArgs()
   * @see #getComparisonExpression()
   * @generated
   */
  EReference getComparisonExpression_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.StringEqualsExpression <em>String Equals Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Equals Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.StringEqualsExpression
   * @generated
   */
  EClass getStringEqualsExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.StringEqualsExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.StringEqualsExpression#getOp()
   * @see #getStringEqualsExpression()
   * @generated
   */
  EAttribute getStringEqualsExpression_Op();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.StringEqualsExpression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.StringEqualsExpression#getArgs()
   * @see #getStringEqualsExpression()
   * @generated
   */
  EReference getStringEqualsExpression_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListIsEmptyExpression <em>List Is Empty Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Is Empty Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListIsEmptyExpression
   * @generated
   */
  EClass getListIsEmptyExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListIsEmptyExpression#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListIsEmptyExpression#getList()
   * @see #getListIsEmptyExpression()
   * @generated
   */
  EReference getListIsEmptyExpression_List();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListExpression <em>List Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListExpression
   * @generated
   */
  EClass getListExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListExpression#getSimple <em>Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Simple</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListExpression#getSimple()
   * @see #getListExpression()
   * @generated
   */
  EReference getListExpression_Simple();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.SimpleList <em>Simple List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple List</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.SimpleList
   * @generated
   */
  EClass getSimpleList();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.SimpleList#getLinked <em>Linked</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Linked</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.SimpleList#getLinked()
   * @see #getSimpleList()
   * @generated
   */
  EReference getSimpleList_Linked();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.LinkedList <em>Linked List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Linked List</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.LinkedList
   * @generated
   */
  EClass getLinkedList();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.LinkedList#getHead <em>Head</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Head</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.LinkedList#getHead()
   * @see #getLinkedList()
   * @generated
   */
  EReference getLinkedList_Head();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.LinkedList#getTail <em>Tail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tail</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.LinkedList#getTail()
   * @see #getLinkedList()
   * @generated
   */
  EReference getLinkedList_Tail();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListOperationExpression <em>List Operation Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Operation Expression</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListOperationExpression
   * @generated
   */
  EClass getListOperationExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListOperationExpression#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListOperationExpression#getList()
   * @see #getListOperationExpression()
   * @generated
   */
  EReference getListOperationExpression_List();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListHeadOp <em>List Head Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Head Op</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListHeadOp
   * @generated
   */
  EClass getListHeadOp();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListTailOp <em>List Tail Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Tail Op</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListTailOp
   * @generated
   */
  EClass getListTailOp();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListConsOp <em>List Cons Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Cons Op</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListConsOp
   * @generated
   */
  EClass getListConsOp();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListConsOp#getElem <em>Elem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elem</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListConsOp#getElem()
   * @see #getListConsOp()
   * @generated
   */
  EReference getListConsOp_Elem();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListLengthOp <em>List Length Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Length Op</em>'.
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ListLengthOp
   * @generated
   */
  EClass getListLengthOp();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ElErrorCosmicoDePaserjFactory getElErrorCosmicoDePaserjFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.MyRacketProgramImpl <em>My Racket Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.MyRacketProgramImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getMyRacketProgram()
     * @generated
     */
    EClass MY_RACKET_PROGRAM = eINSTANCE.getMyRacketProgram();

    /**
     * The meta object literal for the '<em><b>Defines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_RACKET_PROGRAM__DEFINES = eINSTANCE.getMyRacketProgram_Defines();

    /**
     * The meta object literal for the '<em><b>Executions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_RACKET_PROGRAM__EXECUTIONS = eINSTANCE.getMyRacketProgram_Executions();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.DefineImpl <em>Define</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.DefineImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getDefine()
     * @generated
     */
    EClass DEFINE = eINSTANCE.getDefine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINE__NAME = eINSTANCE.getDefine_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINE__PARAMS = eINSTANCE.getDefine_Params();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINE__BODY = eINSTANCE.getDefine_Body();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.SimpleExpressionImpl <em>Simple Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.SimpleExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getSimpleExpression()
     * @generated
     */
    EClass SIMPLE_EXPRESSION = eINSTANCE.getSimpleExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.IntExpressionImpl <em>Int Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.IntExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getIntExpression()
     * @generated
     */
    EClass INT_EXPRESSION = eINSTANCE.getIntExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_EXPRESSION__VALUE = eINSTANCE.getIntExpression_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ArithExpressionImpl <em>Arith Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ArithExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getArithExpression()
     * @generated
     */
    EClass ARITH_EXPRESSION = eINSTANCE.getArithExpression();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARITH_EXPRESSION__OP = eINSTANCE.getArithExpression_Op();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_EXPRESSION__ARGS = eINSTANCE.getArithExpression_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.IfExpressionImpl <em>If Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.IfExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getIfExpression()
     * @generated
     */
    EClass IF_EXPRESSION = eINSTANCE.getIfExpression();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__COND = eINSTANCE.getIfExpression_Cond();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__THEN = eINSTANCE.getIfExpression_Then();

    /**
     * The meta object literal for the '<em><b>Sino</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__SINO = eINSTANCE.getIfExpression_Sino();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.FunctionCallExpressionImpl <em>Function Call Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.FunctionCallExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getFunctionCallExpression()
     * @generated
     */
    EClass FUNCTION_CALL_EXPRESSION = eINSTANCE.getFunctionCallExpression();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL_EXPRESSION__FUNCTION = eINSTANCE.getFunctionCallExpression_Function();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL_EXPRESSION__ARGS = eINSTANCE.getFunctionCallExpression_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.StringExpressionImpl <em>String Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.StringExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getStringExpression()
     * @generated
     */
    EClass STRING_EXPRESSION = eINSTANCE.getStringExpression();

    /**
     * The meta object literal for the '<em><b>St</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_EXPRESSION__ST = eINSTANCE.getStringExpression_St();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ParamsExpressionImpl <em>Params Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ParamsExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getParamsExpression()
     * @generated
     */
    EClass PARAMS_EXPRESSION = eINSTANCE.getParamsExpression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMS_EXPRESSION__NAME = eINSTANCE.getParamsExpression_Name();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ParamsCallExpressionImpl <em>Params Call Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ParamsCallExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getParamsCallExpression()
     * @generated
     */
    EClass PARAMS_CALL_EXPRESSION = eINSTANCE.getParamsCallExpression();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMS_CALL_EXPRESSION__FUNCTION = eINSTANCE.getParamsCallExpression_Function();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanExpressionImpl <em>Boolean Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getBooleanExpression()
     * @generated
     */
    EClass BOOLEAN_EXPRESSION = eINSTANCE.getBooleanExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanConstantImpl <em>Boolean Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanConstantImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getBooleanConstant()
     * @generated
     */
    EClass BOOLEAN_CONSTANT = eINSTANCE.getBooleanConstant();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_CONSTANT__BOOL = eINSTANCE.getBooleanConstant_Bool();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanOpExpressionImpl <em>Boolean Op Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.BooleanOpExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getBooleanOpExpression()
     * @generated
     */
    EClass BOOLEAN_OP_EXPRESSION = eINSTANCE.getBooleanOpExpression();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_OP_EXPRESSION__OP = eINSTANCE.getBooleanOpExpression_Op();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOLEAN_OP_EXPRESSION__ARGS = eINSTANCE.getBooleanOpExpression_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ComparisonExpressionImpl <em>Comparison Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ComparisonExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getComparisonExpression()
     * @generated
     */
    EClass COMPARISON_EXPRESSION = eINSTANCE.getComparisonExpression();

    /**
     * The meta object literal for the '<em><b>Evaluator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON_EXPRESSION__EVALUATOR = eINSTANCE.getComparisonExpression_Evaluator();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON_EXPRESSION__ARGS = eINSTANCE.getComparisonExpression_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.StringEqualsExpressionImpl <em>String Equals Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.StringEqualsExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getStringEqualsExpression()
     * @generated
     */
    EClass STRING_EQUALS_EXPRESSION = eINSTANCE.getStringEqualsExpression();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_EQUALS_EXPRESSION__OP = eINSTANCE.getStringEqualsExpression_Op();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRING_EQUALS_EXPRESSION__ARGS = eINSTANCE.getStringEqualsExpression_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListIsEmptyExpressionImpl <em>List Is Empty Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListIsEmptyExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListIsEmptyExpression()
     * @generated
     */
    EClass LIST_IS_EMPTY_EXPRESSION = eINSTANCE.getListIsEmptyExpression();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_IS_EMPTY_EXPRESSION__LIST = eINSTANCE.getListIsEmptyExpression_List();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListExpressionImpl <em>List Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListExpression()
     * @generated
     */
    EClass LIST_EXPRESSION = eINSTANCE.getListExpression();

    /**
     * The meta object literal for the '<em><b>Simple</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_EXPRESSION__SIMPLE = eINSTANCE.getListExpression_Simple();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.SimpleListImpl <em>Simple List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.SimpleListImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getSimpleList()
     * @generated
     */
    EClass SIMPLE_LIST = eINSTANCE.getSimpleList();

    /**
     * The meta object literal for the '<em><b>Linked</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_LIST__LINKED = eINSTANCE.getSimpleList_Linked();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.LinkedListImpl <em>Linked List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.LinkedListImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getLinkedList()
     * @generated
     */
    EClass LINKED_LIST = eINSTANCE.getLinkedList();

    /**
     * The meta object literal for the '<em><b>Head</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINKED_LIST__HEAD = eINSTANCE.getLinkedList_Head();

    /**
     * The meta object literal for the '<em><b>Tail</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINKED_LIST__TAIL = eINSTANCE.getLinkedList_Tail();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListOperationExpressionImpl <em>List Operation Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListOperationExpressionImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListOperationExpression()
     * @generated
     */
    EClass LIST_OPERATION_EXPRESSION = eINSTANCE.getListOperationExpression();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_OPERATION_EXPRESSION__LIST = eINSTANCE.getListOperationExpression_List();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListHeadOpImpl <em>List Head Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListHeadOpImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListHeadOp()
     * @generated
     */
    EClass LIST_HEAD_OP = eINSTANCE.getListHeadOp();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListTailOpImpl <em>List Tail Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListTailOpImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListTailOp()
     * @generated
     */
    EClass LIST_TAIL_OP = eINSTANCE.getListTailOp();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListConsOpImpl <em>List Cons Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListConsOpImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListConsOp()
     * @generated
     */
    EClass LIST_CONS_OP = eINSTANCE.getListConsOp();

    /**
     * The meta object literal for the '<em><b>Elem</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_CONS_OP__ELEM = eINSTANCE.getListConsOp_Elem();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListLengthOpImpl <em>List Length Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ListLengthOpImpl
     * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.impl.ElErrorCosmicoDePaserjPackageImpl#getListLengthOp()
     * @generated
     */
    EClass LIST_LENGTH_OP = eINSTANCE.getListLengthOp();

  }

} //ElErrorCosmicoDePaserjPackage
