/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.elErrorCosmicoDePaserj;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Is Empty Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListIsEmptyExpression#getList <em>List</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ElErrorCosmicoDePaserjPackage#getListIsEmptyExpression()
 * @model
 * @generated
 */
public interface ListIsEmptyExpression extends BooleanExpression
{
  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(LinkedList)
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ElErrorCosmicoDePaserjPackage#getListIsEmptyExpression_List()
   * @model containment="true"
   * @generated
   */
  LinkedList getList();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.ListIsEmptyExpression#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(LinkedList value);

} // ListIsEmptyExpression
