/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.elErrorCosmicoDePaserj;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Tail Op</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ElErrorCosmicoDePaserjPackage#getListTailOp()
 * @model
 * @generated
 */
public interface ListTailOp extends ListOperationExpression
{
} // ListTailOp
