/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.elErrorCosmicoDePaserj;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.SimpleList#getLinked <em>Linked</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ElErrorCosmicoDePaserjPackage#getSimpleList()
 * @model
 * @generated
 */
public interface SimpleList extends EObject
{
  /**
   * Returns the value of the '<em><b>Linked</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Linked</em>' containment reference.
   * @see #setLinked(LinkedList)
   * @see edu.upb.lp.isc.elErrorCosmicoDePaserj.ElErrorCosmicoDePaserjPackage#getSimpleList_Linked()
   * @model containment="true"
   * @generated
   */
  LinkedList getLinked();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.elErrorCosmicoDePaserj.SimpleList#getLinked <em>Linked</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Linked</em>' containment reference.
   * @see #getLinked()
   * @generated
   */
  void setLinked(LinkedList value);

} // SimpleList
