/*
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.ui;

import com.google.inject.Injector;
import elErrorCosmicoDePaserj.ui.internal.ElErrorCosmicoDePaserjActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ElErrorCosmicoDePaserjExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ElErrorCosmicoDePaserjActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ElErrorCosmicoDePaserjActivator activator = ElErrorCosmicoDePaserjActivator.getInstance();
		return activator != null ? activator.getInjector(ElErrorCosmicoDePaserjActivator.EDU_UPB_LP_ISC_ELERRORCOSMICODEPASERJ) : null;
	}

}
