/*
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyRacketUiModule extends AbstractMyRacketUiModule {

	public MyRacketUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
