/*
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyRacketRuntimeModule extends AbstractMyRacketRuntimeModule {
}
